"""
sandboxerp.engine.time_engine
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Time Engine for SandboxERP — Layer 6.

Assigns temporally coherent dates to ERP transaction chains generated by
the Behaviour Engine.  Every document in a chain respects the causal order
of the business process:

    PO → Receipt → Vendor Bill → Vendor Payment
    Lead → SO → Delivery → Invoice → Payment

Rules enforced:

- Each step occurs **after** its predecessor by a realistic delay.
- Delays are randomised within industry-aware bounds so the dataset
  looks natural rather than mechanical.
- If a transaction carries ``metadata["payment_delay_extra"]`` (injected
  by the :mod:`~sandboxerp.engine.persona_engine`), that value is added
  to the base delay for the ``customer_invoice`` step, producing
  persona-consistent payment behaviour across the dataset.
- All dates fall within a configurable **observation window** (default:
  the 12 months preceding the generation date).
- No document date is in the future.

Usage::

    from sandboxerp.engine.time_engine import assign_dates, ObservationWindow

    window = ObservationWindow.last_n_months(12)
    dated_chain = assign_dates(chain, window=window, rng=random.Random(42))

:author: Hector Colina / Team360 <https://team360.cl>
"""

from __future__ import annotations

import random
from dataclasses import dataclass, field
from datetime import date, timedelta
from typing import Optional


# ─────────────────────────────────────────
# Delay profiles (in calendar days)
# ─────────────────────────────────────────

#: Minimum and maximum delay (days) between consecutive chain steps.
#: Keyed by the *source* step type.
STEP_DELAYS: dict[str, tuple[int, int]] = {
    "lead":             (1, 7),    # lead → sale_order
    "sale_order":       (1, 3),    # SO confirmed → delivery
    "delivery":         (0, 2),    # delivery done → invoice
    "customer_invoice": (0, 30),   # invoice issued → payment (within term)
    "purchase_order":   (3, 21),   # PO sent → receipt (supplier lead time)
    "receipt":          (1, 5),    # receipt validated → vendor bill
    "vendor_bill":      (7, 45),   # vendor bill → vendor payment
    # default for unknown steps
    "_default":         (1, 5),
}


# ─────────────────────────────────────────
# Observation window
# ─────────────────────────────────────────


@dataclass(frozen=True)
class ObservationWindow:
    """A closed date interval within which all generated dates must fall.

    :param start: First valid date (inclusive).
    :param end: Last valid date (inclusive). Must not be in the future.
    """

    start: date
    end: date

    def __post_init__(self) -> None:
        if self.start > self.end:
            raise ValueError(
                f"ObservationWindow start ({self.start}) must be <= end ({self.end})."
            )
        today = date.today()
        if self.end > today:
            object.__setattr__(self, "end", today)

    @classmethod
    def last_n_months(cls, n: int, reference: Optional[date] = None) -> "ObservationWindow":
        """Create a window covering the last *n* calendar months.

        :param n: Number of months to look back (must be >= 1).
        :param reference: Reference date (defaults to today).
        :return: :class:`ObservationWindow` spanning *n* months ending on
            *reference*.
        :raises ValueError: If *n* < 1.
        """
        if n < 1:
            raise ValueError(f"n must be >= 1, got {n}.")
        end = reference or date.today()
        # Approximate: 1 month ≈ 30 days
        start = end - timedelta(days=n * 30)
        return cls(start=start, end=end)

    @property
    def span_days(self) -> int:
        """Total number of days in the window.

        :return: ``(end - start).days``
        """
        return (self.end - self.start).days

    def random_date(self, rng: random.Random) -> date:
        """Return a uniformly random date within the window.

        :param rng: Seeded :class:`random.Random` instance.
        :return: A date between :attr:`start` and :attr:`end` inclusive.
        """
        offset = rng.randint(0, self.span_days)
        return self.start + timedelta(days=offset)

    def clamp(self, d: date) -> date:
        """Clamp *d* so it falls within the window.

        :param d: Date to clamp.
        :return: *d* if within bounds, otherwise the nearest boundary.
        """
        if d < self.start:
            return self.start
        if d > self.end:
            return self.end
        return d


# ─────────────────────────────────────────
# Dated transaction
# ─────────────────────────────────────────


@dataclass
class DatedTransaction:
    """A transaction enriched with a concrete document date.

    :param type: Transaction type (e.g. ``"sale_order"``).
    :param ref: Human-readable reference (e.g. ``"SO/0001"``).
    :param amount: Monetary amount.
    :param parent_ref: Reference of the preceding transaction.
    :param metadata: Arbitrary extra data (may include
        ``payment_delay_extra`` from the Persona Engine).
    :param date: Assigned document date.
    """

    type: str
    ref: str
    amount: float
    parent_ref: Optional[str] = None
    metadata: dict = field(default_factory=dict)
    date: Optional[date] = None

    def as_odoo_date(self) -> str:
        """Return the date formatted for Odoo XML-RPC (``YYYY-MM-DD``).

        :return: ISO 8601 date string, or empty string if date is not set.
        """
        if self.date is None:
            return ""
        return self.date.isoformat()


# ─────────────────────────────────────────
# Core assignment logic
# ─────────────────────────────────────────


def _step_delay(tx, rng: random.Random) -> int:
    """Compute the delay in days after transaction *tx*.

    Uses the base delay from :data:`STEP_DELAYS` for the transaction
    type, then adds ``metadata["payment_delay_extra"]`` if present.
    This allows the :mod:`~sandboxerp.engine.persona_engine` to inject
    persona-specific payment behaviour without modifying the core
    delay table.

    :param tx: Transaction object with ``type`` and ``metadata``
        attributes.
    :param rng: Seeded :class:`random.Random` instance.
    :return: Total delay in days (base + persona extra).
    """
    min_delay, max_delay = STEP_DELAYS.get(tx.type, STEP_DELAYS["_default"])
    base_delay = rng.randint(min_delay, max_delay)
    extra = int(tx.metadata.get("payment_delay_extra", 0)) if tx.metadata else 0
    return base_delay + extra


def assign_dates(
    chain: list,
    *,
    window: ObservationWindow,
    rng: random.Random,
) -> list[DatedTransaction]:
    """Assign temporally coherent dates to a transaction chain.

    The first transaction in the chain gets a random date within *window*.
    Each subsequent transaction is dated *after* its predecessor by a
    delay drawn from :data:`STEP_DELAYS`, plus any
    ``payment_delay_extra`` stored in the transaction's metadata (set by
    the :mod:`~sandboxerp.engine.persona_engine` for invoice steps).

    If a computed date would exceed ``window.end`` the chain is
    compressed: the overflow is distributed backwards so all dates
    remain within the window.

    :param chain: List of transaction objects with at least ``type``,
        ``ref``, ``amount``, ``parent_ref``, and ``metadata`` attributes.
    :param window: :class:`ObservationWindow` constraining valid dates.
    :param rng: Seeded :class:`random.Random` for reproducibility.
    :return: New list of :class:`DatedTransaction` with dates assigned.
    """
    if not chain:
        return []

    # Estimate total minimum span needed for the chain, including any
    # persona-injected extra delays already present in metadata.
    min_span = sum(
        STEP_DELAYS.get(tx.type, STEP_DELAYS["_default"])[0]
        + int(tx.metadata.get("payment_delay_extra", 0) if tx.metadata else 0)
        for tx in chain[:-1]
    )

    # Pick a start date that leaves enough room for the full chain
    latest_start = window.end - timedelta(days=min_span)
    if latest_start < window.start:
        latest_start = window.start

    anchor_window = ObservationWindow(start=window.start, end=latest_start)
    current_date = anchor_window.random_date(rng)

    dated: list[DatedTransaction] = []

    for i, tx in enumerate(chain):
        dated.append(
            DatedTransaction(
                type=tx.type,
                ref=tx.ref,
                amount=tx.amount,
                parent_ref=tx.parent_ref,
                metadata=dict(tx.metadata),
                date=window.clamp(current_date),
            )
        )

        if i < len(chain) - 1:
            delay = _step_delay(chain[i], rng)
            current_date = current_date + timedelta(days=delay)

    return dated


def assign_dates_to_chains(
    chains: list[list],
    *,
    window: ObservationWindow,
    rng: random.Random,
) -> list[list[DatedTransaction]]:
    """Assign dates to a collection of transaction chains.

    Convenience wrapper around :func:`assign_dates` for bulk processing.

    :param chains: List of chains as returned by
        :func:`~sandboxerp.engine.behaviour.generate_chain`.
    :param window: :class:`ObservationWindow` constraining valid dates.
    :param rng: Seeded :class:`random.Random` for reproducibility.
    :return: List of dated chains.
    """
    return [assign_dates(chain, window=window, rng=rng) for chain in chains]
